AWSTemplateFormatVersion: 2010-09-09
Description: Template to Create a CodeCommit Repo

Parameters:
  RepoName:
    Type: String
    Description: Name of CodeCommit Repo
    Default: ""
  EnvironmentTag:
    Type: String
    Default: ""
  NameTag:
    Type: String
    Default: ""
    
Resources:
  DevOpsCodePipelineRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName  
      Tags: 
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Name
          Value: !Ref NameTag


Outputs:
  DevOpsCodePipelineRepoName: 
    Description: CodeCommit Repo Name
    Value: !GetAtt DevOpsCodePipelineRepo.Name
    Export:
      Name: DevOpsCodePipelineRepoName

  DevOpsCodePipelineRepoHTTPCloneURL:
    Description: CodeCommit Repo HTTP Clone URL
    Value: !GetAtt DevOpsCodePipelineRepo.CloneUrlHttp
    Export:
      Name: DevOpsCodePipelineRepoHTTPCloneURL