AWSTemplateFormatVersion: 2010-09-09
Description: Template to Create a CodeCommit Repo

Parameters:
  RepoName:
    Type: String
    Description: Name of CodeCommit Repo
    Default: ""

Resources:
  DevOpsCodePipelineRepo:
    Type: AWS::CodeCommit::Repository
    Properties:
      RepositoryName: !Ref RepoName  

Outputs:
  DevOpsCodePipelineRepoName: 
    Description: CodeCommit Repo Name
    Value: !GetAtt DevOpsCodePipelineRepo.Name
    Export:
      Name: DevOpsCodePipelineRepoName

  DevOpsCodePipelineRepoHTTPCloneURL:
    Description: CodeCommit Repo HTTP Clone URL
    Value: !GetAtt DevOpsCodePipelineRepo.CloneUrlHttp
    Export:
      Name: DevOpsCodePipelineRepoHTTPCloneURL