AWSTemplateFormatVersion: 2010-09-09
Description: Template to Create an S3 Bucket with versioning

Parameters:
  BucketName:
    Type: String
    Description: S3 Bucket Name
    Default: ""

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref BucketName
      VersioningConfiguration:
        Status: Enabled
      Tags: 
        - Key: Environment
          Value: Development
        - Key: Name
          Value: Pipeline Artifact Bucket

Outputs:
  PipelineArtifactBucket:
    Description: CodePipeline Artifact Bucket Name
    Value: !Ref BucketName
    Export:
      Name: PipelineArtifactBucket