AWSTemplateFormatVersion: 2010-09-09
Description: Template to create a CodeBuild Project

Parameters:
  BuildProjectName:
    Type: String
    Description: Name of CodeBuild Project
    Default: ""
  EnvironmentTag:
    Type: String
    Default: ""
  NameTag:
    Type: String
    Default: ""
Resources:
  DevOpsCodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Ref BuildProjectName
      Description: Build App
      ServiceRole: !GetAtt [ DevOpsCodeBuildRole, Arn ]
      Artifacts:
        Type: S3
        Name: !Ref BuildProjectName        
        Location: !ImportValue PipelineArtifactBucket
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/java:openjdk-11
      Source:
        Location: !Sub 
          - https://git-codecommit.${AWS::Region}.amazonaws.com/v1/repos/${DevOpsCodePipelineRepoName}
          - DevOpsCodePipelineRepoName: !ImportValue DevOpsCodePipelineRepoName
        Type: CODECOMMIT
      TimeoutInMinutes: 15
      Tags: 
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Name
          Value: !Ref NameTag

  DevOpsCodeBuildRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: DevOpsCodeBuildRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codebuild.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /service-role/
      Policies:
        - PolicyName: DevOpsCodeCommitPolicy
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              - Effect: "Allow"
                Action:
                  - "codecommit:GitPull"
                Resource: !Sub
                  - arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${DevOpsCodePipelineRepoName}
                  - DevOpsCodePipelineRepoName: !ImportValue DevOpsCodePipelineRepoName
              - Effect: "Allow"
                Action:
                  - "logs:CreateLogGroup"
                  - "logs:CreateLogStream"
                  - "logs:PutLogEvents"
                Resource: !Sub arn:aws:logs:${AWS::Region}:${AWS::AccountId}:log-group:/aws/codebuild/*
              - Effect: "Allow"
                Action:
                  - "s3:PutObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"                  
                Resource:
                  - !Sub arn:aws:s3:::codepipeline-${AWS::Region}-*
                  - !Sub 
                    - arn:aws:s3:::${PipelineArtifactBucket}/*
                    - PipelineArtifactBucket: !ImportValue PipelineArtifactBucket
                  - !Sub 
                    - arn:aws:s3:::${PipelineArtifactBucket}
                    - PipelineArtifactBucket: !ImportValue PipelineArtifactBucket

Outputs:
  DevOpsCodeBuildRole:
    Description: CodeBuild Role Name
    Value: !Ref DevOpsCodeBuildRole
    Export:
      Name: DevOpsCodeBuildRole

  BuildProjectName:
    Description: CodeBuild Project Name
    Value: !Ref BuildProjectName
    Export:
      Name: BuildProjectName