AWSTemplateFormatVersion: 2010-09-09
Description: Template to create CodePipeline with associated rules and Policies

Parameters:
  TeamName:
    Type: String
    Description: Name of the Team
  ApplicationName:
    Type: String
    Description: Name of the Application 
  RepoName:
    Type: String
    Description: Name of the CodeCommit Repo
  BucketName:
    Type: String
    Description: Bucket where the artifact can be found.
  SQSStackName:
    Type: String
    Description: SQS stack name.

Resources:
  CodePipelineAppRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CodePipelineAppRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "CodePipelineAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:DeleteObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:GetBucketPolicy"
                Resource:
                  - !Sub 
                    - arn:aws:s3:::${PipelineArtifactBucket}/*
                    - PipelineArtifactBucket: !ImportValue PipelineArtifactBucket
                  - !Sub 
                    - arn:aws:s3:::${PipelineArtifactBucket}
                    - PipelineArtifactBucket: !ImportValue PipelineArtifactBucket
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'  
                  - 'cloudformation:UpdateStack'  
                  - 'cloudformation:DescribeStacks'  
                  - 'cloudformation:DescribeStackEvents'  
                  - 'cloudformation:DescribeChangeSet'  
                  - 'cloudformation:ExecuteChangeSet'  
                Resource: '*'
              - Effect: "Allow"
                Action:
                  - "codecommit:ListBranches"
                  - "codecommit:ListRepositories"
                  - "codecommit:BatchGetRepositories"
                  - "codecommit:Get*"
                  - "codecommit:GitPull"
                  - "codecommit:UploadArchive"
                Resource: !Sub
                  - arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${DevOpsCodePipelineRepoName}
                  - DevOpsCodePipelineRepoName: !ImportValue DevOpsCodePipelineRepoName
              - Effect: "Allow"
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource:
                  - !Sub
                    - arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${BuildProjectName}
                    - BuildProjectName: !ImportValue BuildProjectName
                  - !Sub
                    - arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:build/${BuildProjectName}:*
                    - BuildProjectName: !ImportValue BuildProjectName
              - Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource: '*'
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource:
                  - arn:aws:iam::971996090633:role/cicdpipelineCFrole

  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub DevOpsCICDPipeline
      RoleArn: !GetAtt [ CodePipelineAppRole, Arn ]
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: ApplicationOutput
              Configuration:
                BranchName: master
                RepositoryName: !ImportValue DevOpsCodePipelineRepoName
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: ApplicationOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: CodeBuildArtifact
              Configuration:
                ProjectName: !ImportValue BuildProjectName
              RunOrder: 1

        - Name: Deploy_SQS
          Actions:
           - Name: DeployToDev
             ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
          # OutputArtifacts:
             InputArtifacts:
              - Name: CodeBuildArtifact
             Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: 'CAPABILITY_IAM, CAPABILITY_NAMED_IAM, CAPABILITY_AUTO_EXPAND'
              RoleArn: !Sub arn:aws:iam::971996090633:role/cicdpipelineCFrole
              StackName: !Ref SQSStackName
              TemplatePath: sqs-cfn.yaml
              TemplateConfiguration: ".params/sqs-param.json"
             RunOrder: 1


        # - Name: Deploy_To_Dev
        #   Actions:
        #     - Name: DeployToDev
        #       InputArtifacts:
        #         - Name: CodeBuildArtifact
        #       # ActionTypeId:
        #       #   Category: Deploy
        #       #   Owner: AWS
        #       #   Version: 1
        #       #   Provider: CloudFormation
        #       Configuration:
        #         ApplicationName: !ImportValue CodeDeployApp
        #       RunOrder: 1
            # - Name: ManualApproval
            #   # :Actions
            #   #  - Name: ManualApproval
            #   ActionTypeId:
            #     Category: Approval
            #     Owner: AWS
            #     Version: 1
            #     Provider: Manual
            #   # Configuration:
            #   #   NotificationArn: !Ref CodePipelineSNSTopic
            #   #   CustomData: Approve Production deployment
            #   RunOrder: 1
             # - Name: DeployToProd
        #   Actions:
        #     - Name: DeployToProd
        #       InputArtifacts:
        #         - Name: CodeBuildArtifact
        #       ActionTypeId:
        #         Category: Deploy
        #         Owner: AWS
        #         Version: 1
        #         Provider: CodeDeploy
        #       Configuration:
        #         ApplicationName: !ImportValue CodeDeployApplication
        #         DeploymentGroupName: !ImportValue CodeDeployProdDeploymentGroup
        #       RunOrder: 1

      ArtifactStore:
        Type: S3
        Location: !ImportValue PipelineArtifactBucket