AWSTemplateFormatVersion: 2010-09-09
Description: Template to create CodePipeline with associated rules and Policies and deploye services

Parameters: 
  RepoName:
    Type: String
    Description: Name of the CodeCommit Repo
  BucketName:
    Type: String
    Description: Bucket where the artifact can be found.
  SQSStackName:
    Type: String
    Description: SQS stack name.
  S3StackName:
    Type: String
    Description: S3 stack name.
  GlueStackName:
    Type: String
    Description: Glue stack name.
  LambdaStackName:
    Type: String
    Description: Lambda stack name.
  MapingStackName:
    Type: String
    Description: Maping stack name.
  AthenaStackName:
    Type: String
    Description: Athena stack name.
  EnvironmentTag:
    Type: String
    Default: ""
  NameTag:
    Type: String
    Default: ""
  AccIdBdcpractice:
    Type: String
    Description: Acc Id of bdc

Resources:
  CodePipelineAppRole:
    Type: "AWS::IAM::Role"
    Properties:
      RoleName: CodePipelineAppRole
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service:
                - "codepipeline.amazonaws.com"
            Action:
              - "sts:AssumeRole"
      Path: /
      Policies:
        - PolicyName: "CodePipelineAccessPolicy"
          PolicyDocument:
            Version: "2012-10-17"
            Statement:
              -
                Effect: "Allow"
                Action:
                  - "s3:DeleteObject"
                  - "s3:GetObject"
                  - "s3:GetObjectVersion"
                  - "s3:ListBucket"
                  - "s3:PutObject"
                  - "s3:GetBucketPolicy"
                  - "s3:*"
                Resource:
                  - !Sub 
                    - arn:aws:s3:::${PipelineArtifactBucket}/*
                    - PipelineArtifactBucket: !ImportValue PipelineArtifactBucket
                  - !Sub 
                    - arn:aws:s3:::${PipelineArtifactBucket}
                    - PipelineArtifactBucket: !ImportValue PipelineArtifactBucket
              - Effect: "Allow"
                Action:
                  - "sns:Publish"
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'cloudformation:CreateStack'  
                  - 'cloudformation:UpdateStack'  
                  - 'cloudformation:DescribeStacks'  
                  - 'cloudformation:DescribeStackEvents'  
                  - 'cloudformation:DescribeChangeSet'  
                  - 'cloudformation:ExecuteChangeSet'  
                Resource: '*'
              - Effect: "Allow"
                Action:
                  - "codecommit:ListBranches"
                  - "codecommit:ListRepositories"
                  - "codecommit:BatchGetRepositories"
                  - "codecommit:Get*"
                  - "codecommit:GitPull"
                  - "codecommit:UploadArchive"
                Resource: !Sub
                  - arn:aws:codecommit:${AWS::Region}:${AWS::AccountId}:${DevOpsCodePipelineRepoName}
                  - DevOpsCodePipelineRepoName: !ImportValue DevOpsCodePipelineRepoName
              - Effect: "Allow"
                Action:
                  - "codebuild:StartBuild"
                  - "codebuild:BatchGetBuilds"
                Resource:
                  - !Sub
                    - arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:project/${BuildProjectName}
                    - BuildProjectName: !ImportValue BuildProjectName
                  - !Sub
                    - arn:aws:codebuild:${AWS::Region}:${AWS::AccountId}:build/${BuildProjectName}:*
                    - BuildProjectName: !ImportValue BuildProjectName
              - Effect: Allow
                Action:
                  - 'codedeploy:CreateDeployment'
                  - 'codedeploy:GetApplicationRevision'
                  - 'codedeploy:GetDeployment'
                  - 'codedeploy:GetDeploymentConfig'
                  - 'codedeploy:RegisterApplicationRevision'
                Resource: '*'
              - Effect: "Allow"
                Action:
                  - "iam:PassRole"
                Resource:
                  # - arn:aws:iam::971996090633:role/cicdpipelineCFrole
                  - !Sub arn:aws:iam::${AccIdBdcpractice}:role/cicdpipelineCFrole

  CodePipeline:
    Type: "AWS::CodePipeline::Pipeline"
    Properties:
      Name: !Sub DevOpsCICDPipeline
      RoleArn: !GetAtt [ CodePipelineAppRole, Arn ]
      Tags: 
        - Key: Environment
          Value: !Ref EnvironmentTag
        - Key: Name
          Value: !Ref NameTag
      Stages:
        - Name: Source
          Actions:
            - Name: ApplicationSource
              ActionTypeId:
                Category: Source
                Owner: AWS
                Version: 1
                Provider: CodeCommit
              OutputArtifacts:
                - Name: ApplicationOutput
              Configuration:
                BranchName: master
                RepositoryName: !ImportValue DevOpsCodePipelineRepoName
              RunOrder: 1
        - Name: Build
          Actions:
            - Name: CodeBuild
              InputArtifacts:
                - Name: ApplicationOutput
              ActionTypeId:
                Category: Build
                Owner: AWS
                Version: 1
                Provider: CodeBuild
              OutputArtifacts:
                - Name: CodeBuildArtifact
              Configuration:
                ProjectName: !ImportValue BuildProjectName
              RunOrder: 1

        - Name: Deploy_SQS
          Actions:
           - Name: DeployToDev
             ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
             InputArtifacts:
              - Name: CodeBuildArtifact
             Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !Sub arn:aws:iam::${AccIdBdcpractice}:role/cicdpipelineCFrole
              StackName: !Ref SQSStackName
              TemplatePath: CodeBuildArtifact::Iac/sqs-cfn.yaml
              TemplateConfiguration: CodeBuildArtifact::Params/sqs-param.json
             RunOrder: 1

        - Name: Deploy_S3
          Actions:
           - Name: DeployToDev
             ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
             InputArtifacts:
              - Name: CodeBuildArtifact
             Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !Sub arn:aws:iam::${AccIdBdcpractice}:role/cicdpipelineCFrole
              StackName: !Ref S3StackName
              TemplatePath: CodeBuildArtifact::Iac/s3-cfn.yaml
              TemplateConfiguration: CodeBuildArtifact::Params/s3-param.json
             RunOrder: 2

        - Name: Deploy_Glue
          Actions:
           - Name: DeployToDev
             ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
             InputArtifacts:
              - Name: CodeBuildArtifact
             Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !Sub arn:aws:iam::${AccIdBdcpractice}:role/cicdpipelineCFrole
              StackName: !Ref GlueStackName
              TemplatePath: CodeBuildArtifact::Iac/glue-cfn.yaml
              TemplateConfiguration: CodeBuildArtifact::Params/glue-param.json
             RunOrder: 3		

        - Name: Deploy_Lambda
          Actions:
           - Name: DeployToDev
             ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
             InputArtifacts:
              - Name: CodeBuildArtifact
             Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !Sub arn:aws:iam::${AccIdBdcpractice}:role/cicdpipelineCFrole
              StackName: !Ref LambdaStackName
              TemplatePath: CodeBuildArtifact::Iac/lambda-cfn.yaml
              TemplateConfiguration: CodeBuildArtifact::Params/lambda-param.json
             RunOrder: 4

        - Name: Deploy_SourceMaping
          Actions:
           - Name: DeployToDev
             ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
             InputArtifacts:
              - Name: CodeBuildArtifact
             Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !Sub arn:aws:iam::${AccIdBdcpractice}:role/cicdpipelineCFrole
              StackName: !Ref MapingStackName
              TemplatePath: CodeBuildArtifact::Iac/event-source-maping-cfn.yaml
             RunOrder: 5

        - Name: Deploy_Athena
          Actions:
           - Name: DeployToDev
             ActionTypeId:
              Category: Deploy
              Owner: AWS
              Version: 1
              Provider: CloudFormation
             InputArtifacts:
              - Name: CodeBuildArtifact
             Configuration:
              ActionMode: CREATE_UPDATE
              Capabilities: CAPABILITY_NAMED_IAM,CAPABILITY_AUTO_EXPAND
              RoleArn: !Sub arn:aws:iam::${AccIdBdcpractice}:role/cicdpipelineCFrole
              StackName: !Ref AthenaStackName
              TemplatePath: CodeBuildArtifact::Iac/athena-cfn.yaml
              TemplateConfiguration: CodeBuildArtifact::Params/athena-param.json
             RunOrder: 5              

      ArtifactStore:
        Type: S3
        Location: !ImportValue PipelineArtifactBucket