version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file Iac/sqs-cfn.yaml --s3-bucket pipelineartifactbucket09072023 --output-template-file outputsqstemplate.yaml      
artifacts:
  type: zip
  files:
    - Iac/sqs-cfn.yaml
    # - DevOpsIacRepo/sqs-cfn.yaml
    - outputsqstemplate.yaml
    - Params/sqs-param.json
    # - DevOpsIacRepo/params/sqs-param.json
    
