version: 0.1
phases:
  install:
    commands:
      - aws cloudformation package --template-file CodeDeploy.yaml --s3-bucket ccdemoappartifactbucket08092023 --output-template-file outputSamTemplate.yaml
artifacts:
  type: zip
  files:
    - outputSamTemplate.yaml